variable ENV {}
variable "COMMON_TAGS" {}
variable "COGNITO_DOMAIN_NAME" {}
variable "AWS_REGION" {}
variable "CURRENT_ACCOUNT_ID" {}
variable "IAM_COGNITO_ASSUMABLE_ROLE_EXTERNAL_ID" {}
variable "EMAIL_SENDER" {}
variable "COGNITO_GROUP_LIST" {}
variable "WEBAPP_DNS" {}
variable "RESOURCE_PREFIX" {}
